export enum RegistrationStage {
  STARTED = 'STARTED',
  BASIC_PROFILE = 'BASIC_PROFILE',
  LOCATION_INFO = 'LOCATION_INFO',
  PHOTOS = 'PHOTOS',
  MUSIC_PREFERENCES = 'MUSIC_PREFERENCES',
  LIFESTYLE = 'LIFESTYLE',
  PERSONALITY = 'PERSONALITY',
  DATING_PREFERENCES = 'DATING_PREFERENCES',
  PRIVACY_SETTINGS = 'PRIVACY_SETTINGS',
  FINISHED = 'FINISHED',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  NON_BINARY = 'NON_BINARY',
  OTHER = 'OTHER',
  PREFER_NOT_TO_SAY = 'PREFER_NOT_TO_SAY',
}

export enum SexualOrientation {
  STRAIGHT = 'STRAIGHT',
  GAY = 'GAY',
  LESBIAN = 'LESBIAN',
  BISEXUAL = 'BISEXUAL',
  PANSEXUAL = 'PANSEXUAL',
  ASEXUAL = 'ASEXUAL',
  DEMISEXUAL = 'DEMISEXUAL',
  QUEER = 'QUEER',
  QUESTIONING = 'QUESTIONING',
  OTHER = 'OTHER',
}

export enum ConcertFrequency {
  NEVER = 'NEVER',
  RARELY = 'RARELY',
  FEW_TIMES_A_YEAR = 'FEW_TIMES_A_YEAR',
  MONTHLY = 'MONTHLY',
  WEEKLY = 'WEEKLY',
  MULTIPLE_TIMES_A_WEEK = 'MULTIPLE_TIMES_A_WEEK',
}

export enum MusicImportance {
  NOT_IMPORTANT = 'NOT_IMPORTANT',
  SOMEWHAT_IMPORTANT = 'SOMEWHAT_IMPORTANT',
  IMPORTANT = 'IMPORTANT',
  VERY_IMPORTANT = 'VERY_IMPORTANT',
  LIFE_IS_MUSIC = 'LIFE_IS_MUSIC',
}

export enum RelationshipGoal {
  CASUAL_DATING = 'CASUAL_DATING',
  SERIOUS_RELATIONSHIP = 'SERIOUS_RELATIONSHIP',
  FRIENDSHIP = 'FRIENDSHIP',
  SOMETHING_CASUAL = 'SOMETHING_CASUAL',
  MARRIAGE = 'MARRIAGE',
  FIGURING_IT_OUT = 'FIGURING_IT_OUT',
  PREFER_NOT_TO_SAY = 'PREFER_NOT_TO_SAY',
}

export enum SmokingHabits {
  NON_SMOKER = 'NON_SMOKER',
  SOCIAL_SMOKER = 'SOCIAL_SMOKER',
  REGULAR_SMOKER = 'REGULAR_SMOKER',
  TRYING_TO_QUIT = 'TRYING_TO_QUIT',
  PREFER_NOT_TO_SAY = 'PREFER_NOT_TO_SAY',
}

export enum DrinkingHabits {
  NON_DRINKER = 'NON_DRINKER',
  SOCIAL_DRINKER = 'SOCIAL_DRINKER',
  MODERATE_DRINKER = 'MODERATE_DRINKER',
  REGULAR_DRINKER = 'REGULAR_DRINKER',
  PREFER_NOT_TO_SAY = 'PREFER_NOT_TO_SAY',
}

export enum ExerciseFrequency {
  NEVER = 'NEVER',
  RARELY = 'RARELY',
  ONCE_A_WEEK = 'ONCE_A_WEEK',
  FEW_TIMES_A_WEEK = 'FEW_TIMES_A_WEEK',
  DAILY = 'DAILY',
  MULTIPLE_TIMES_DAILY = 'MULTIPLE_TIMES_DAILY',
}

export enum EducationLevel {
  HIGH_SCHOOL = 'HIGH_SCHOOL',
  SOME_COLLEGE = 'SOME_COLLEGE',
  ASSOCIATES_DEGREE = 'ASSOCIATES_DEGREE',
  BACHELORS_DEGREE = 'BACHELORS_DEGREE',
  MASTERS_DEGREE = 'MASTERS_DEGREE',
  DOCTORATE = 'DOCTORATE',
  TRADE_SCHOOL = 'TRADE_SCHOOL',
  PREFER_NOT_TO_SAY = 'PREFER_NOT_TO_SAY',
}

export enum RelationshipStatus {
  SINGLE = 'SINGLE',
  DIVORCED = 'DIVORCED',
  WIDOWED = 'WIDOWED',
  SEPARATED = 'SEPARATED',
  PREFER_NOT_TO_SAY = 'PREFER_NOT_TO_SAY',
}

export enum KidsPreference {
  WANTS_KIDS = 'WANTS_KIDS',
  DOESNT_WANT_KIDS = 'DOESNT_WANT_KIDS',
  HAS_KIDS = 'HAS_KIDS',
  HAS_KIDS_WANTS_MORE = 'HAS_KIDS_WANTS_MORE',
  HAS_KIDS_DOESNT_WANT_MORE = 'HAS_KIDS_DOESNT_WANT_MORE',
  OPEN_TO_KIDS = 'OPEN_TO_KIDS',
  NOT_SURE = 'NOT_SURE',
  PREFER_NOT_TO_SAY = 'PREFER_NOT_TO_SAY',
}

export enum MBTI {
  ISFJ = 'ISFJ',
  ISFP = 'ISFP',
  ISTJ = 'ISTJ',
  ISTP = 'ISTP',
  INFJ = 'INFJ',
  INFP = 'INFP',
  INTJ = 'INTJ',
  INTP = 'INTP',
  ESFJ = 'ESFJ',
  ESFP = 'ESFP',
  ESTJ = 'ESTJ',
  ESTP = 'ESTP',
  ENFJ = 'ENFJ',
  ENFP = 'ENFP',
  ENTJ = 'ENTJ',
  ENTP = 'ENTP',
}

export enum Religion {
  CHRISTIAN = 'CHRISTIAN',
  MUSLIM = 'MUSLIM',
  JEWISH = 'JEWISH',
  HINDU = 'HINDU',
  BUDDHIST = 'BUDDHIST',
  SIKH = 'SIKH',
  ATHEIST = 'ATHEIST',
  AGNOSTIC = 'AGNOSTIC',
  SPIRITUAL = 'SPIRITUAL',
  OTHER = 'OTHER',
  PREFER_NOT_TO_SAY = 'PREFER_NOT_TO_SAY',
}

export enum PoliticalViews {
  LIBERAL = 'LIBERAL',
  PROGRESSIVE = 'PROGRESSIVE',
  MODERATE = 'MODERATE',
  CONSERVATIVE = 'CONSERVATIVE',
  LIBERTARIAN = 'LIBERTARIAN',
  SOCIALIST = 'SOCIALIST',
  APOLITICAL = 'APOLITICAL',
  OTHER = 'OTHER',
  PREFER_NOT_TO_SAY = 'PREFER_NOT_TO_SAY',
}
